### ISSUE TITLE
Rating video does not remove video from "rate-later list"

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol-mobile#10]
All my rate-later videos have now received at least 3 ratings by me, but they're still in my "rate-later list" 😅

**Comment by tchaumeny** [comment]
As [discussed on Discord](https://discord.com/channels/760540475139817472/834689634042380328/838340802728034366), this should be implemented in the backend (and then removed from website front).

Maybe this could be implemented within the `save` method of the [ExpertRatingsSerializerV2](https://github.com/tournesol-app/tournesol/blob/master/backend/backend/api_v2/expert_ratings.py#L76):

```python
class ExpertRatingsSerializerV2(serializers.HyperlinkedModelSerializer):
    ...

    def save(self, **kwargs):
        super().save(**kwargs)
        # Remove self.validated_data['video_1'] and self.validated_data['video_2'] from rate later list
    ...
```

**Comment by tchaumeny** [comment]
See https://github.com/tournesol-app/tournesol/issues/74
